#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bank
#    username: root
#    password: 123456
#
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: com.zyChen.bank.model  # ????
#  mapper-locations: classpath:mapper/*.xml     # ????

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.zychen.bank.model
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: bank-system-jwt-secret-key-2024-abcdefghijklmnopqrstuvwxyz
  expiration: 86400000
  token-header: Authorization
  token-prefix: "Bearer "

app:
  password:
    min-length: 6
    max-length: 15